// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
/**
 * Documentos generated by hbm2java
 */
@SuppressWarnings("serial")
public class Documentos implements java.io.Serializable {

	private Integer idDocu;
	private String path;

	public Documentos() {
	}

	public Documentos(String path) {
		this.path = path;
	}

	public Integer getIdDocu() {
		return this.idDocu;
	}

	public void setIdDocu(Integer idDocu) {
		this.idDocu = idDocu;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
