// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
import java.util.Date;

/**
 * Ficherosexportados generated by hbm2java
 */
@SuppressWarnings("serial")
public class Ficherosexportados implements java.io.Serializable {

	private Long id;
	private Date fecha;
	private String filepath;
	private Long iduser;

	public Ficherosexportados() {
	}

	public Ficherosexportados(Date fecha, String filepath, Long iduser) {
		this.fecha = fecha;
		this.filepath = filepath;
		this.iduser = iduser;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public Long getIduser() {
		return this.iduser;
	}

	public void setIduser(Long iduser) {
		this.iduser = iduser;
	}

}
