// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
import java.util.Date;

import jcolibri.cbrcore.Attribute;
import jcolibri.cbrcore.CaseComponent;

/**
 * Mediciones generated by hbm2java
 */
@SuppressWarnings("serial")
public class Mediciones implements java.io.Serializable,  CaseComponent {

	private Integer idMedicion;
	private int idPaciente;
	private Date fechaMedicion;
	private Double adehiper;
	private Double adehipo;
	private Double ddhiper;
	private Double ddhipo;
	private Double mmhiper;
	private Double mmhipo;
	private Double dcohiper;
	private Double dcohipo;
	private Double mhiper;
	private Double mhipo;
	private Double dcehiper;
	private Double dcehipo;
	private Double adohiper;
	private Double adohipo;

	public Mediciones() {
	}

	public Mediciones(int idPaciente, Date fechaMedicion) {
		this.idPaciente = idPaciente;
		this.fechaMedicion = fechaMedicion;
	}

	public Mediciones(int idPaciente, Date fechaMedicion, Double adehiper, Double adehipo, Double ddhiper,
			Double ddhipo, Double mmhiper, Double mmhipo, Double dcohiper, Double dcohipo, Double mhiper, Double mhipo,
			Double dcehiper, Double dcehipo, Double adohiper, Double adohipo) {
		this.idPaciente = idPaciente;
		this.fechaMedicion = fechaMedicion;
		this.adehiper = adehiper;
		this.adehipo = adehipo;
		this.ddhiper = ddhiper;
		this.ddhipo = ddhipo;
		this.mmhiper = mmhiper;
		this.mmhipo = mmhipo;
		this.dcohiper = dcohiper;
		this.dcohipo = dcohipo;
		this.mhiper = mhiper;
		this.mhipo = mhipo;
		this.dcehiper = dcehiper;
		this.dcehipo = dcehipo;
		this.adohiper = adohiper;
		this.adohipo = adohipo;
	}

	public Integer getIdMedicion() {
		return this.idMedicion;
	}

	public void setIdMedicion(Integer idMedicion) {
		this.idMedicion = idMedicion;
	}

	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	public Date getFechaMedicion() {
		return this.fechaMedicion;
	}

	public void setFechaMedicion(Date fechaMedicion) {
		this.fechaMedicion = fechaMedicion;
	}

	public Double getAdehiper() {
		return this.adehiper;
	}

	public void setAdehiper(Double adehiper) {
		this.adehiper = adehiper;
	}

	public Double getAdehipo() {
		return this.adehipo;
	}

	public void setAdehipo(Double adehipo) {
		this.adehipo = adehipo;
	}

	public Double getDdhiper() {
		return this.ddhiper;
	}

	public void setDdhiper(Double ddhiper) {
		this.ddhiper = ddhiper;
	}

	public Double getDdhipo() {
		return this.ddhipo;
	}

	public void setDdhipo(Double ddhipo) {
		this.ddhipo = ddhipo;
	}

	public Double getMmhiper() {
		return this.mmhiper;
	}

	public void setMmhiper(Double mmhiper) {
		this.mmhiper = mmhiper;
	}

	public Double getMmhipo() {
		return this.mmhipo;
	}

	public void setMmhipo(Double mmhipo) {
		this.mmhipo = mmhipo;
	}

	public Double getDcohiper() {
		return this.dcohiper;
	}

	public void setDcohiper(Double dcohiper) {
		this.dcohiper = dcohiper;
	}

	public Double getDcohipo() {
		return this.dcohipo;
	}

	public void setDcohipo(Double dcohipo) {
		this.dcohipo = dcohipo;
	}

	public Double getMhiper() {
		return this.mhiper;
	}

	public void setMhiper(Double mhiper) {
		this.mhiper = mhiper;
	}

	public Double getMhipo() {
		return this.mhipo;
	}

	public void setMhipo(Double mhipo) {
		this.mhipo = mhipo;
	}

	public Double getDcehiper() {
		return this.dcehiper;
	}

	public void setDcehiper(Double dcehiper) {
		this.dcehiper = dcehiper;
	}

	public Double getDcehipo() {
		return this.dcehipo;
	}

	public void setDcehipo(Double dcehipo) {
		this.dcehipo = dcehipo;
	}

	public Double getAdohiper() {
		return this.adohiper;
	}

	public void setAdohiper(Double adohiper) {
		this.adohiper = adohiper;
	}

	public Double getAdohipo() {
		return this.adohipo;
	}

	public void setAdohipo(Double adohipo) {
		this.adohipo = adohipo;
	}
	
	public String toString() 
    {
		return "[Parámetros "+adehiper+" "+ adehipo+" "+ddhiper+" "+ddhipo+" "+mmhiper+" "+mmhipo+" "+dcohiper+" "+dcohipo+" "+mhiper+" "+
					mhipo+ " "+ dcehiper+" "+dcehipo+" "+adohiper+" "+adohipo+" "+"]";
    }
	
	@Override
	public Attribute getIdAttribute() {
		return new Attribute("idMedicion",this.getClass());
	}

}
