// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
import java.util.Date;

/**
 * MensajesUsuario generated by hbm2java
 */
@SuppressWarnings("serial")
public class MensajesUsuario implements java.io.Serializable {

	private Integer mensajeid;
	private Date fecha;
	private Boolean nuevo;
	private Integer recomendacionid;
	private Long userid;

	public MensajesUsuario() {
	}

	public MensajesUsuario(Date fecha, Boolean nuevo, Integer recomendacionid, Long userid) {
		this.fecha = fecha;
		this.nuevo = nuevo;
		this.recomendacionid = recomendacionid;
		this.userid = userid;
	}

	public Integer getMensajeid() {
		return this.mensajeid;
	}

	public void setMensajeid(Integer mensajeid) {
		this.mensajeid = mensajeid;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Boolean getNuevo() {
		return this.nuevo;
	}

	public void setNuevo(Boolean nuevo) {
		this.nuevo = nuevo;
	}

	public Integer getRecomendacionid() {
		return this.recomendacionid;
	}

	public void setRecomendacionid(Integer recomendacionid) {
		this.recomendacionid = recomendacionid;
	}

	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

}
