// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
/**
 * RecomendacionesId generated by hbm2java
 */
@SuppressWarnings("serial")
public class RecomendacionesId implements java.io.Serializable {

	private int idRec;
	private int idSol;

	public RecomendacionesId() {
	}

	public RecomendacionesId(int idRec, int idSol) {
		this.idRec = idRec;
		this.idSol = idSol;
	}

	public int getIdRec() {
		return this.idRec;
	}

	public void setIdRec(int idRec) {
		this.idRec = idRec;
	}

	public int getIdSol() {
		return this.idSol;
	}

	public void setIdSol(int idSol) {
		this.idSol = idSol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecomendacionesId))
			return false;
		RecomendacionesId castOther = (RecomendacionesId) other;

		return (this.getIdRec() == castOther.getIdRec()) && (this.getIdSol() == castOther.getIdSol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRec();
		result = 37 * result + this.getIdSol();
		return result;
	}

}
