// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
import java.util.Date;

/**
 * Recomendaciones generated by hbm2java
 */
@SuppressWarnings("serial")
public class Recomendaciones implements java.io.Serializable {

	private RecomendacionesId id;
	private int idPac;
	private int idDes;
	private int idActi;
	private Date fecha;
	private boolean enviada;
	private boolean leida;

	public Recomendaciones() {
	}

	public Recomendaciones(RecomendacionesId id, int idPac, int idDes, int idActi, Date fecha, boolean enviada, boolean leida) {
		this.id = id;
		this.idPac = idPac;
		this.idDes = idDes;
		this.idActi = idActi;
		this.fecha = fecha;
		this.enviada = enviada;
		this.leida = leida;
	}

	public RecomendacionesId getId() {
		return this.id;
	}

	public void setId(RecomendacionesId id) {
		this.id = id;
	}

	public int getIdPac() {
		return this.idPac;
	}

	public void setIdPac(int idPac) {
		this.idPac = idPac;
	}

	public int getIdDes() {
		return this.idDes;
	}

	public void setIdDes(int idDes) {
		this.idDes = idDes;
	}
	
	public int getIdActi() {
		return this.idActi;
	}

	public void setIdActi(int idActi) {
		this.idActi = idActi;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean isEnviada() {
		return this.enviada;
	}

	public void setEnviada(boolean enviada) {
		this.enviada = enviada;
	}

	public boolean isLeida() {
		return this.leida;
	}

	public void setLeida(boolean leida) {
		this.leida = leida;
	}

}
