// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
/**
 * Solucionrec generated by hbm2java
 */
@SuppressWarnings("serial")
public class Solucionrec implements java.io.Serializable {

	private Integer idSol;
	private String texto;
	private int idDocu;
	private String categoria;

	public Solucionrec() {
	}

	public Solucionrec(String texto, int idDocu, String categoria) {
		this.texto = texto;
		this.idDocu = idDocu;
		this.categoria = categoria;
	}

	public Integer getIdSol() {
		return this.idSol;
	}

	public void setIdSol(Integer idSol) {
		this.idSol = idSol;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public int getIdDocu() {
		return this.idDocu;
	}

	public void setIdDocu(int idDocu) {
		this.idDocu = idDocu;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

}
