// default package
// Generated 14-may-2017 1:22:01 by Hibernate Tools 5.2.1.Final

package beans;
import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
@SuppressWarnings("serial")
public class Usuarios implements java.io.Serializable {

	private Long id;
	private String address;
	private Byte altacurso;
	private String city;
	private Date date;
	private String dni;
	private String email;
	private Long examen;
	private Date fechaevaluacion;
	private Boolean firmacontrato;
	private Double height;
	private Long iddoctor;
	private String ip;
	private Long login;
	private Integer moodleid;
	private String name;
	private Integer nivel;
	private String password;
	private String phone;
	private String phone2;
	private Integer rolcurso;
	private String sex;
	private String surname1;
	private String surname2;
	private Date fechaconsen;
	private Integer hipergluc;
	private Integer hipogluc;
	private String colegiado;

	public Usuarios() {
	}

	public Usuarios(String address, Byte altacurso, String city, Date date, String dni, String email, Long examen,
			Date fechaevaluacion, Boolean firmacontrato, Double height, Long iddoctor, String ip, Long login,
			Integer moodleid, String name, Integer nivel, String password, String phone, String phone2,
			Integer rolcurso, String sex, String surname1, String surname2, Date fechaconsen, Integer hipergluc,
			Integer hipogluc, String colegiado) {
		this.address = address;
		this.altacurso = altacurso;
		this.city = city;
		this.date = date;
		this.dni = dni;
		this.email = email;
		this.examen = examen;
		this.fechaevaluacion = fechaevaluacion;
		this.firmacontrato = firmacontrato;
		this.height = height;
		this.iddoctor = iddoctor;
		this.ip = ip;
		this.login = login;
		this.moodleid = moodleid;
		this.name = name;
		this.nivel = nivel;
		this.password = password;
		this.phone = phone;
		this.phone2 = phone2;
		this.rolcurso = rolcurso;
		this.sex = sex;
		this.surname1 = surname1;
		this.surname2 = surname2;
		this.fechaconsen = fechaconsen;
		this.hipergluc = hipergluc;
		this.hipogluc = hipogluc;
		this.colegiado = colegiado;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Byte getAltacurso() {
		return this.altacurso;
	}

	public void setAltacurso(Byte altacurso) {
		this.altacurso = altacurso;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getExamen() {
		return this.examen;
	}

	public void setExamen(Long examen) {
		this.examen = examen;
	}

	public Date getFechaevaluacion() {
		return this.fechaevaluacion;
	}

	public void setFechaevaluacion(Date fechaevaluacion) {
		this.fechaevaluacion = fechaevaluacion;
	}

	public Boolean getFirmacontrato() {
		return this.firmacontrato;
	}

	public void setFirmacontrato(Boolean firmacontrato) {
		this.firmacontrato = firmacontrato;
	}

	public Double getHeight() {
		return this.height;
	}

	public void setHeight(Double height) {
		this.height = height;
	}

	public Long getIddoctor() {
		return this.iddoctor;
	}

	public void setIddoctor(Long iddoctor) {
		this.iddoctor = iddoctor;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Long getLogin() {
		return this.login;
	}

	public void setLogin(Long login) {
		this.login = login;
	}

	public Integer getMoodleid() {
		return this.moodleid;
	}

	public void setMoodleid(Integer moodleid) {
		this.moodleid = moodleid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public Integer getRolcurso() {
		return this.rolcurso;
	}

	public void setRolcurso(Integer rolcurso) {
		this.rolcurso = rolcurso;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSurname1() {
		return this.surname1;
	}

	public void setSurname1(String surname1) {
		this.surname1 = surname1;
	}

	public String getSurname2() {
		return this.surname2;
	}

	public void setSurname2(String surname2) {
		this.surname2 = surname2;
	}

	public Date getFechaconsen() {
		return this.fechaconsen;
	}

	public void setFechaconsen(Date fechaconsen) {
		this.fechaconsen = fechaconsen;
	}

	public Integer getHipergluc() {
		return this.hipergluc;
	}

	public void setHipergluc(Integer hipergluc) {
		this.hipergluc = hipergluc;
	}

	public Integer getHipogluc() {
		return this.hipogluc;
	}

	public void setHipogluc(Integer hipogluc) {
		this.hipogluc = hipogluc;
	}

	public String getColegiado() {
		return this.colegiado;
	}

	public void setColegiado(String colegiado) {
		this.colegiado = colegiado;
	}

}
